# Ruff configuration for the Chat API project

target-version = "py312"
line-length = 100

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # Line too long (handled by formatter)
    "B904",  # raise-without-from-inside-except (acceptable in this context)
]

[lint.per-file-ignores]
"api/tests/*.py" = ["F401", "F841"]  # Allow unused imports and variables in tests

[lint.isort]
known-first-party = ["api"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
